# -*- coding: utf-8 -*-
"""
Created on Fri Apr 24 16:36:58 2020

@author: magicolas
"""

NANOSECONDS = 1
MICROSECONDS= 1000 * NANOSECONDS
MILLISECONDS= 1000 * MICROSECONDS
SECONDS= 1000* MILLISECONDS

MINE_RATE= 4* SECONDS

STARTING_BALANCE= 1000

MINING_REWARD= 50
MINING_REWARD_INPUT= {'address': '*--official-mining-reward--*'}